### ISSUE TITLE
可否完善一下有关10.0版本的api文档

### ISSUE THREAD

**Issue by PonderFox0643** [MCSManager/Documentation#56]
9.x的api内容很多
10.0功能这么多的话api应该也不少吧...

**Comment by unitwk** [comment]
> 9.x的api内容很多 10.0功能这么多的话api应该也不少吧...

9.X 的 API 基本上在 10.X 全部可以使用，只是参数改变了，remote_uuid 改成了 daemon_id。

**Comment by unitwk** [comment]
文档方面暂时没有时间写。

**Comment by PonderFox0643** [comment]
> 文档方面暂时没有时间写。

可以直接搬到新文档里吗（）

**Comment by unitwk** [comment]
Done
